using DBAssistant.UseCases.Models;
using DBAssistant.UseCases.Ports;

namespace DBAssistant.Api.IntegrationTests.Acceptance;

/// <summary>
/// Provides a deterministic SQL-generation gateway for acceptance testing.
/// </summary>
public sealed class AcceptanceSqlGenerationGateway : ISqlGenerationGateway
{
    private readonly IReadOnlyDictionary<string, AcceptanceScenario> _scenarios;

    /// <summary>
    /// Initializes a new instance of the <see cref="AcceptanceSqlGenerationGateway"/> class.
    /// </summary>
    /// <param name="scenarios">The acceptance scenarios keyed by question text.</param>
    public AcceptanceSqlGenerationGateway(IReadOnlyDictionary<string, AcceptanceScenario> scenarios)
    {
        _scenarios = scenarios;
    }

    /// <summary>
    /// Returns the deterministic SQL configured for the supplied natural-language question.
    /// </summary>
    /// <param name="question">The natural-language question.</param>
    /// <param name="schemaContext">The assembled schema context, not used by the fake gateway.</param>
    /// <param name="cancellationToken">The cancellation token used to stop the fake call.</param>
    /// <returns>The deterministic SQL result associated with the question.</returns>
    public Task<GeneratedSqlResult> GenerateSqlAsync(string question, string schemaContext, CancellationToken cancellationToken)
    {
        if (_scenarios.TryGetValue(question, out var scenario) is false)
        {
            throw new InvalidOperationException($"No acceptance scenario was configured for question: {question}");
        }

        return Task.FromResult(new GeneratedSqlResult
        {
            CanAnswer = true,
            Sql = scenario.Sql,
            Explanation = "Deterministic SQL generated by the acceptance test gateway."
        });
    }

    /// <summary>
    /// Returns a deterministic human-friendly summary for the executed acceptance query result.
    /// </summary>
    /// <param name="question">The original natural-language question.</param>
    /// <param name="sql">The validated SQL executed by the use case.</param>
    /// <param name="executionResult">The direct database result returned by the acceptance flow.</param>
    /// <param name="cancellationToken">The cancellation token used to stop the fake call.</param>
    /// <returns>A deterministic summary that confirms the result size.</returns>
    public Task<QueryResultNarration> GenerateResultsAsTextAsync(
        string question,
        string sql,
        QueryExecutionResult executionResult,
        CancellationToken cancellationToken)
    {
        return Task.FromResult(new QueryResultNarration
        {
            ResultsAsText = $"Acceptance summary for '{question}' with {executionResult.Rows.Count} row(s)."
        });
    }
}
