using DBAssistant.Domain.Exceptions;

namespace DBAssistant.Domain.Entities;

/// <summary>
/// Represents a validated read-only SQL statement that is safe to execute against a connected database.
/// </summary>
public sealed partial class SqlStatement
{
    private const string SELECT_KEYWORD = "SELECT";
    private const string WITH_KEYWORD = "WITH";

    private static readonly string[] AllowedStartingKeywords =
    [
        SELECT_KEYWORD,
        WITH_KEYWORD
    ];

    private static readonly string[] ForbiddenKeywords =
    [
        "ALTER",
        "CALL",
        "CREATE",
        "DELETE",
        "DROP",
        "EXEC",
        "GRANT",
        "INSERT",
        "MERGE",
        "REPLACE",
        "REVOKE",
        "TRUNCATE",
        "UPDATE"
    ];

    /// <summary>
    /// Initializes a new instance of the <see cref="SqlStatement"/> class with an already validated SQL payload.
    /// </summary>
    /// <param name="value">The normalized SQL statement.</param>
    private SqlStatement(string value)
    {
        Value = value;
    }

    /// <summary>
    /// Gets the normalized SQL text that passed the read-only validation rules.
    /// </summary>
    public string Value { get; }

    /// <summary>
    /// Validates the provided SQL and returns a read-only statement wrapper when the SQL is allowed.
    /// </summary>
    /// <param name="sql">The SQL text generated by the application flow.</param>
    /// <returns>A validated <see cref="SqlStatement"/> instance.</returns>
    /// <exception cref="DomainValidationException">Thrown when the SQL is empty or contains non-read-only operations.</exception>
    public static SqlStatement CreateReadOnly(string sql)
    {
        if (string.IsNullOrWhiteSpace(sql))
        {
            throw new DomainValidationException("The generated SQL cannot be empty.");
        }

        var normalizedSql = sql.Trim();
        var firstKeyword = normalizedSql
            .Split([' ', '\n', '\r', '\t'], StringSplitOptions.RemoveEmptyEntries)
            .FirstOrDefault()?
            .ToUpperInvariant();

        if (firstKeyword is null || AllowedStartingKeywords.Contains(firstKeyword) is false)
        {
            throw new DomainValidationException("Only SELECT statements and CTE-based read-only queries are allowed.");
        }

        foreach (var forbiddenKeyword in ForbiddenKeywords)
        {
            if (ContainsForbiddenKeyword(normalizedSql, forbiddenKeyword))
            {
                throw new DomainValidationException($"Forbidden SQL keyword detected: {forbiddenKeyword}.");
            }
        }

        return new SqlStatement(normalizedSql);
    }

    /// <summary>
    /// Detects whether a forbidden SQL keyword exists in the provided statement using simple boundary heuristics.
    /// </summary>
    /// <param name="sql">The SQL text to inspect.</param>
    /// <param name="keyword">The forbidden keyword being searched.</param>
    /// <returns><see langword="true"/> when the keyword is found as an executable token; otherwise, <see langword="false"/>.</returns>
    private static bool ContainsForbiddenKeyword(string sql, string keyword)
    {
        return sql.Contains($" {keyword} ", StringComparison.OrdinalIgnoreCase) ||
               sql.Contains($"\n{keyword} ", StringComparison.OrdinalIgnoreCase) ||
               sql.Contains($"\t{keyword} ", StringComparison.OrdinalIgnoreCase) ||
               sql.StartsWith($"{keyword} ", StringComparison.OrdinalIgnoreCase) ||
               sql.EndsWith($" {keyword}", StringComparison.OrdinalIgnoreCase) ||
               sql.Contains($"({keyword} ", StringComparison.OrdinalIgnoreCase);
    }
}
